### ISSUE TITLE
the clocks color not changing  

### ISSUE THREAD

**Issue by 14kaitou** [jere-ortega24/gnome-shell-extension-oclock#1]
I like the idea of bringing the clock to analog way of simplicity so it doesn't eat up the upper middle panel(chough... just my opinion) but the color doesn't seem to change hope you could enhance the extension, it's a pretty cool one.

**Comment by jere-ortega24** [comment]
Did you disable the option use theme colors?
If you did what OS do you have? And what gnome version?
It has worked on all the systems I have tried it, but maybe I can give it a look.

**Comment by 14kaitou** [comment]
> Did you disable the option use theme colors? 

hi thank you for replying, I forgot that it still inherits the default theme
> If you did what OS do you have? And what gnome version?

I'm on ubuntu 20.04.1 gnome-shell 3.36 it works wonderfully 

> It has worked on all the systems I have tried it, but maybe I can give it a look.

thanks for considering it, I test this on arch and fedora with gnome-shell 3.38 and it works fine
